#pragma once

// Process exit codes
#define PAVRPGM_ERROR_BAD_ARGS 1
#define PAVRPGM_ERROR_OPERATION_FAILED 2
#define PAVRPGM_ERROR_DEVICE_NOT_FOUND 3
#define PAVRPGM_ERROR_DEVICE_MULTIPLE_FOUND 4
