// This header file contains constants needed to use the USB, serial, and I2C
// protocols.

#ifndef _TIC_PROTOCOL_H
#define _TIC_PROTOCOL_H

#define TIC_MIN_ALLOWED_ACCEL 100
#define TIC_MAX_ALLOWED_ACCEL 0x7FFFFFFF
#define TIC_MAX_ALLOWED_SPEED 500000000  // 50 kHz

#define TIC_SPEED_UNITS_PER_HZ 10000
#define TIC_ACCEL_UNITS_PER_HZ2 100

#define TIC_CONTROL_MODE_SERIAL 0
#define TIC_CONTROL_MODE_STEP_DIR 1
#define TIC_CONTROL_MODE_RC_POSITION 2
#define TIC_CONTROL_MODE_RC_SPEED 3
#define TIC_CONTROL_MODE_ANALOG_POSITION 4
#define TIC_CONTROL_MODE_ANALOG_SPEED 5
#define TIC_CONTROL_MODE_ENCODER_POSITION 6
#define TIC_CONTROL_MODE_ENCODER_SPEED 7

#define TIC_SCALING_DEGREE_LINEAR 0
#define TIC_SCALING_DEGREE_QUADRATIC 1
#define TIC_SCALING_DEGREE_CUBIC 2

#define TIC_MICROSTEPPING_MODE_1 0
#define TIC_MICROSTEPPING_MODE_2 1
#define TIC_MICROSTEPPING_MODE_4 2
#define TIC_MICROSTEPPING_MODE_8 3
#define TIC_MICROSTEPPING_MODE_16 4
#define TIC_MICROSTEPPING_MODE_32 5

#define TIC_DECAY_MODE_MIXED 0
#define TIC_DECAY_MODE_SLOW 1
#define TIC_DECAY_MODE_FAST 2

#define TIC_PIN_SERIAL 7
#define TIC_PIN_PULLUP 6
#define TIC_PIN_ANALOG 5
#define TIC_PIN_ACTIVE_HIGH 3
#define TIC_PIN_SWITCH_POSN 0
#define TIC_PIN_SWITCH_MASK 0x07
#define TIC_PIN_SWITCH_NONE 0
#define TIC_PIN_SWITCH_LIMIT_FORWARD 1
#define TIC_PIN_SWITCH_LIMIT_REVERSE 2
#define TIC_PIN_SWITCH_HOME 3
#define TIC_PIN_SWITCH_KILL 4

#define TIC_CMD_GET_DEBUG_DATA 0x80
#define TIC_CMD_PING 0x89
#define TIC_CMD_START_BOOTLOADER 0xFF
#define TIC_CMD_WRITE_SETTING 0x8A
#define TIC_CMD_READ_SETTING 0x8C
#define TIC_CMD_REINITIALIZE 0x8F

#define TIC_SETTING_NOT_INITIALIZED 0x00
#define TIC_SETTING_CONTROL_MODE 0x01
#define TIC_SETTING_NEVER_SLEEP 0x02
#define TIC_SETTING_DISABLE_SAFE_START 0x03
#define TIC_SETTING_IGNORE_ERR_LINE_HIGH 0x04
#define TIC_SETTING_SERIAL_BAUD_RATE_GENERATOR 0x05
#define TIC_SETTING_SERIAL_DEVICE_NUMBER 0x07
#define TIC_SETTING_I2C_DEVICE_ADDRESS 0x08
#define TIC_SETTING_COMMAND_TIMEOUT 0x09
#define TIC_SETTING_SERIAL_CRC_ENABLED 0x0B
#define TIC_SETTING_LOW_VIN_TIMEOUT 0x0C
#define TIC_SETTING_LOW_VIN_SHUTOFF_VOLTAGE 0x0E
#define TIC_SETTING_LOW_VIN_STARTUP_VOLTAGE 0x10
#define TIC_SETTING_HIGH_VIN_SHUTOFF_VOLTAGE 0x12
#define TIC_SETTING_VIN_MULTIPLIER_OFFSET 0x14
#define TIC_SETTING_RC_MAX_PULSE_PERIOD 0x16
#define TIC_SETTING_RC_BAD_SIGNAL_TIMEOUT 0x18
#define TIC_SETTING_RC_CONSECUTIVE_GOOD_PULSES 0x1A
#define TIC_SETTING_INPUT_PLAY 0x1B
#define TIC_SETTING_INPUT_ERROR_MIN 0x1C
#define TIC_SETTING_INPUT_ERROR_MAX 0x1E
#define TIC_SETTING_INPUT_SCALING_DEGREE 0x20
#define TIC_SETTING_INPUT_INVERT 0x21
#define TIC_SETTING_INPUT_MIN 0x22
#define TIC_SETTING_INPUT_NEUTRAL_MIN 0x24
#define TIC_SETTING_INPUT_NEUTRAL_MAX 0x26
#define TIC_SETTING_INPUT_MAX 0x28
#define TIC_SETTING_OUTPUT_MIN 0x2A
#define TIC_SETTING_OUTPUT_NEUTRAL 0x2E
#define TIC_SETTING_OUTPUT_MAX 0x32
#define TIC_SETTING_ENCODER_PRESCALER 0x36
#define TIC_SETTING_ENCODER_POSTSCALER 0x37
#define TIC_SETTING_SCL_CONFIG 0x3B
#define TIC_SETTING_SDA_CONFIG 0x3C
#define TIC_SETTING_TX_CONFIG 0x3D
#define TIC_SETTING_RX_CONFIG 0x3E
#define TIC_SETTING_RC_CONFIG 0x3F
#define TIC_SETTING_CURRENT_LIMIT 0x40
#define TIC_SETTING_MICROSTEPPING_MODE 0x41
#define TIC_SETTING_DECAY_MODE 0x42
#define TIC_SETTING_SPEED_MIN 0x43
#define TIC_SETTING_SPEED_MAX 0x47
#define TIC_SETTING_DECEL_MAX 0x4B
#define TIC_SETTING_ACCEL_MAX 0x4F
#define TIC_SETTING_DECEL_MAX_DURING_ERROR 0x54  // TODO: pack this better
#define TIC_HIGHEST_SETTING_ADDRESS 0x57

#define TIC_CURRENT_LIMIT_UNITS_MA 32

#define TIC_BAUD_RATE_GENERATOR_FACTOR 12000000

#endif
